apiVersion: storage.spotahome.com/v1alpha2
kind: RedisFailover
metadata:
  name: kyrre-persistent
  labels:
    team: aura
spec:
  sentinel:
    replicas: 3
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 128Mi
  redis:
    image: redis
    version: 5.0.4-alpine
    exporter: true
    replicas: 3
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 128Mi
    storage:
      persistentVolumeClaim:
        metadata:
          name: kyrre-rf-persistent
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
